name: main2

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution in Dataverse environment"
        required: true
        default: MicaSolution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: test2
        id: test2
        uses: actions/github-script@v5
        env:
          CONTEXT_TO_USE: build-deploy
          TARGET_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          script: |
            let test = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main2.yml',
              per_page: 1
            })

            console.log(test.data.total_count)
            if (test.data.total_count != 0) {
              console.log(test.data.workflow_runs[0].status)
              console.log(test.data.workflow_runs[0].conclusion)
            }
