name: main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: test
        id: test
        uses: actions/github-script@v5
        env:
          CONTEXT_TO_USE: build-deploy
          TARGET_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          script: |
            console.log(process.env.CONTEXT_TO_USE)
            console.log(process.env.TARGET_URL)

            let test = await github.rest.actions.getWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main.yml'
            })

            console.log(test)
