name: main

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "name of the Solution in Dataverse environment"
        required: true
        default: MicaSolution
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: test
        id: test
        uses: actions/github-script@v5
        env:
          CONTEXT_TO_USE: build-deploy
          TARGET_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main.yml',
              ref: '${{ github.ref }}',
              inputs: {
                solution_name: '${{ github.event.inputs.solution_name }}'
              }
            })

            let test = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main.yml',
              per_page: 1
            })

            console.log(test.data.total_count)
            console.log(test.data.workflow_runs[0].status)
            console.log(test.data.workflow_runs[0].conclusion)
